### ISSUE TITLE
very slow decoding

### ISSUE THREAD

**Issue by jungmoona** [WestHillApps/UniGif#7]
I have a question
Is there any way to improve decoder performance?
For example I decoded gif 1080x1080.
Decoding time spent more than 10 seconds.

**Comment by stetttho** [comment]
UniGif is nice for small and simple gifs, but for more complicated gifs you should consider buying this asset instead: https://assetstore.unity.com/packages/tools/animation/gif2textures-12074 

I changed from UniGif to Gif2Textures and gifs which took 10 seconds to load before now load within 1 second. Also an issue I had with transparent GIF is solved by this plugin.

**Comment by jungmoona** [comment]
thanx for you answer
